version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: ali12345
      POSTGRES_DB: signupdb
      POSTGRES_HOST:  db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always

  backend:
    image: signup-backend:latest
    command: sh ./docker-entrypoint.sh
    environment:
      POSTGRES_PASSWORD: ali12345
      POSTGRES_USERNAME: ali
      POSTGRES_HOST: db
      POSTGRES_DATABASE: signupdb
    depends_on:
      - db
    ports:
      - 4000:4000

  frontend:
    image: signup-frontend:latest
    depends_on:
      - backend
    ports:
      - 80:80